# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lustre-LFS
version:      0.01
version_from: lib/Lustre/LFS.pm
installdirs:  site
requires:
    IO::Dir:                       0
    IO::File:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
